version: '3'
services:
  certbot:
    image: certbot/certbot
    ports: 
        - 5000:80
        - 5001:443
    depends_on:
      - "nginx"
    volumes:
      - ${PWD}/certbot_wrapper.sh:/certbot_wrapper.sh:ro
      - ${PWD}/config.src:/config.src:ro
      - ${PWD}/include_ssl/:/etc/nginx/include_ssl/:rw
      - letsencrypt:/etc/letsencrypt:rw
      - /var/run/docker.sock:/tmp/docker.sock
    entrypoint: /bin/ash 
    command: /certbot_wrapper.sh
