version: '3'
services:
  nginx:
    image: nginx:1-alpine
    ports: 
        - 80:80
        - 443:443
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/www:/usr/share/nginx/html:ro
      - ${PWD}/include_ssl/:/etc/nginx/include_ssl/:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt: